### ISSUE TITLE
Link to code of conduct not resolved on website

### ISSUE THREAD

**Issue by alessandrofelder** [EllaKaye/communers#30]

**Comment by thomaszwagerman** [comment]
CONTRIBUTING.md is linking to a CODE_OF_CONDUCT.md file, but this file does not exist in the repo yet. Is it in a branch that is yet to be merged?

**Comment by EllaKaye** [comment]
No, there's no `CODE_OF_CONDUCT.md` file anywhere. I think this link must have been present in the template that @SaranjeetKaur used for `CONTRIBUTING.md`. Saranjeet, would you be able to proposed a PR adding a `CODE_OF_CONDUCT.md` file as well?

**Comment by SaranjeetKaur** [comment]
@EllaKaye , @alessandrofelder - Yes, the link is in the `CONTRIBUTING.md` file. Should we go with a contributor covenant code of conduct? Or something else? We might also need an email address for reporting any violations of the code of conduct. 

Or for now, should we go with CW24's code of conduct? In which case, I can remove that line from `CONTRIBUTING.md`?

**Comment by EllaKaye** [comment]
I'd lean towards the [contributor covenant CoC](https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md), since it should be familiar and uncontroversial for people working in Open Source. The [CW24 CoC](https://www.software.ac.uk/cw24-participation-guidelines) has specifics around it being an event, whereas I think of communeRS now as more of an open source project/community than an event. Essentially, the principles in both are similar, so I don't think it makes a huge difference. @SaranjeetKaur, would you be willing to be the contact for it?

**Comment by SaranjeetKaur** [comment]
Hi @EllaKaye, I don't mind to be a point of contact. But I would want to avoid putting my personal email address there. It might be useful to setup a dedicated email address for this. I also feel that having more than one person monitoring the CoC would be a more sustainable approach.

**Comment by EllaKaye** [comment]
Agreed. I've set up communers.community@gmail.com which we can use for the group. I'll share password with you privately when back at my work computer next week. I'm happy to be listed with you as a name for CoC contact, and would be good to have a third person for that too. I'll raise that in the Slack.
